import React from 'react'
import Link from 'next/link'

export default function About() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12">
      <h1 className="text-3xl font-bold text-gray-900 mb-2">About</h1>
      <p className="text-gray-500 mb-10">
        Learn what this app is, why it was built, and what makes it different.
      </p>

      {/* What is it */}
      <div className="mb-8">
        <h2 className="text-lg font-semibold text-gray-900 mb-2">What is InterviewAI?</h2>
        <p className="text-gray-500 text-sm leading-relaxed">
          InterviewAI is a free AI-powered mock interview platform built to help job seekers
          practice and improve before their real interviews. Whether you are a fresher or
          an experienced professional, the app generates custom interview questions based
          on your job role and experience level, and gives you detailed feedback on every answer.
        </p>
      </div>

      {/* Why it was built */}
      <div className="mb-8">
        <h2 className="text-lg font-semibold text-gray-900 mb-2">Why was it built?</h2>
        <p className="text-gray-500 text-sm leading-relaxed">
          Most people fail interviews not because they lack skills, but because they lack
          practice. Hiring a personal interview coach is expensive. InterviewAI gives everyone
          access to unlimited, personalized mock interview practice — completely free.
        </p>
      </div>

      {/* What makes it different */}
      <div className="mb-8">
        <h2 className="text-lg font-semibold text-gray-900 mb-2">What makes it different?</h2>
        <ul className="flex flex-col gap-3 mt-3">
          {[
            'Questions are generated by Gemini AI tailored to your exact job role and experience',
            'Answer using your voice — just like a real interview',
            'Get a rating and detailed feedback for every single answer',
            'Review all past interviews anytime from your dashboard',
            'Completely free to use',
          ].map((point) => (
            <li key={point} className="flex gap-3 items-start text-sm text-gray-500">
              <span className="mt-0.5 w-2 h-2 rounded-full bg-indigo-400 shrink-0"></span>
              {point}
            </li>
          ))}
        </ul>
      </div>

      {/* Tech stack */}
      <div className="mb-10">
        <h2 className="text-lg font-semibold text-gray-900 mb-2">Built with</h2>
        <div className="flex gap-2 flex-wrap">
          {['Next.js', 'Tailwind CSS', 'Clerk Auth', 'Gemini AI', 'Drizzle ORM', 'Neon PostgreSQL'].map((tech) => (
            <span key={tech} className="text-xs bg-gray-100 text-gray-600 px-3 py-1.5 rounded-full font-medium">
              {tech}
            </span>
          ))}
        </div>
      </div>

      <Link href="/dashboard" className="inline-block bg-indigo-600 text-white text-sm font-medium px-5 py-2 rounded-lg hover:bg-indigo-700 transition-colors">
        Go to Dashboard
      </Link>
    </div>
  )
}